name: Install Python Dependencies
description: Install Python dependencies for specific environment specified
inputs:
  python-version:
    description: Python version
    required: true
  group:
    description: Python group dependencies to install (i.e. "test", "lint", "docs")
    required: false

runs:
  using: composite
  steps:
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -
      shell: bash

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: "poetry"

    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      shell: bash
      run: |
        poetry install --no-interaction --only main
        if [ -n "${{ inputs.group }}" ]
        then poetry install --no-interaction --only ${{ inputs.group }}
        fi
